### ISSUE TITLE
Project drop down list, shouldn't be closed after selecting an other project.

### ISSUE THREAD

**Issue by Chris2011** [sickill/off-plugin#22]
Atm I open the dropDownList to select an other project. Usually I use my keyboard to navigate through. For this I use arrow down or up and than the dropDownList closes after selecting an other project and the indexing part starts. I would like to select each project what I would like and the dropDown should cloes after pressing space or an other key. The problem is, when the first project is selected and I want to navigate to the 4th project, I have to reopen the dropDownList and this is not really intuitive for me.

**Comment by markiewb** [comment]
@Chris2011: Can you post a gif of the issue. I don't see the problem.

**Comment by Chris2011** [comment]
![openfilefastdropdown](https://cloud.githubusercontent.com/assets/795658/13492978/71e62f38-e13b-11e5-8786-7a4ce38fb28c.gif)

As you can see, I use the arrow keys to navigate through the list of items inside the selectbox (Arrowkeys because of using my keyboard more than my mouse). After one item is selected, the DropDownBox closes and i have to reopen it and select the next one. My intentions todo were to use arrow keys while the DropDownList should stay open and after hit enter or hit space than the list should be closed and the indexing can starts.

**Comment by markiewb** [comment]
Reproducible.

**Comment by markiewb** [comment]
Fixed in 1.3
@Chris2011 you can get a snapshot from the releases tab

**Comment by Chris2011** [comment]
Works as expected.
