### ISSUE TITLE
Provide a signed package for 8.1

### ISSUE THREAD

**Issue by markiewb** [sickill/off-plugin#24]

**Comment by mjomble** [comment]
Hi, I'm no longer maintaining this project as I've stopped using NetBeans and started using Atom (which has a feature like this built in).

Pull requests are welcome (the project's readme describes how to build it), but if anyone who activels uses NetBeans wants to take over the project, I think we can arrange that :)

**Comment by markiewb** [comment]
@mjomble: I will take over the project, if you let me. Please rank me up to collaborator for this project, so that I can modify and close issues. I did the same for https://github.com/dzsessona/QuickOpener-NetBeans 

This way all the current users can keep their installed plugin and I provide a plugin with the same codebasename. All the issue handling will be here.

**Comment by mjomble** [comment]
Cool! I don't have full access to this repo's settings, but I've notified the original author.

If you leave your e-mail address here (or some other means of private messaging) and sickill agrees, I'll also send you the netbeans.org credentials you can use to publish new versions of the plugin.

**Comment by markiewb** [comment]
@mjomble @sickill : Thanks for giving me the user rights to manage the project and to push to the repo. Thank you for your trust!

I do not need your credentials. I will publish it as a new plugin using the same code base name. The users won't notice that. I will also update the readme.md accordingly.

**Comment by sickill** [comment]
@markiewb thanks for your contribution!

**Comment by markiewb** [comment]
Released here http://plugins.netbeans.org/plugin/63478/?show=true

**Comment by markiewb** [comment]
Uploading images to be used in README.md
![2016-03-20_19h30_02](https://cloud.githubusercontent.com/assets/1857095/13906271/9b8c8004-eed2-11e5-8a16-25e5445eb51f.png)
![2016-03-20_19h30_39](https://cloud.githubusercontent.com/assets/1857095/13906272/9c5d21d2-eed2-11e5-9d2b-8b1a64219ef4.png)
