### ISSUE TITLE
Dialog opens on the wrong monitor (dual monitor setup)

### ISSUE THREAD

**Issue by Chris2011** [sickill/off-plugin#36]
OFF plugin opens on the, I think primary monitor, but my netbeans is on the secondary monitor. It should opens in the middle of the screen, what it did AND inside the netbeans window, as the other go to ... dialogs.

**Comment by markiewb** [comment]
I tried to fix it blindly in 1.3.0.2-SN. I could not try it out using my single monitor setup at home. So please test!

**Comment by Chris2011** [comment]
It works, but now it opens not in the middle, it is on top of the IDE and if I don't have any open files, it opens on bottom.

**Comment by Chris2011** [comment]
I expect, that it should open in the middle.

**Comment by markiewb** [comment]
Second try. I updated the logic. Now the dialog is shown in the center of the NB window, which has the input focus.

Fixed in 1.3.0.4-SN

**Comment by markiewb** [comment]
@Chris2011: Please try again

**Comment by Chris2011** [comment]
Works as expected, thx.
