### ISSUE TITLE
Don't disable controls while indexing

### ISSUE THREAD

**Issue by Chris2011** [sickill/off-plugin#38]
When I accidentally select a project, OFF blocks almost everything in this plugin, I can't change the project in the JComboBox. I expect that I can cancel the indexing while changing the project, so that the indexing will run after switch the project inside JComboBox.

**Comment by markiewb** [comment]
I introduced that behaviour recently. I will remove the disabling of the controls

**Comment by markiewb** [comment]
Fixed in 1.3-SN

**Comment by Chris2011** [comment]
Works as expected.
