### ISSUE TITLE
Does not index anything in 8.1

### ISSUE THREAD

**Issue by tinyclanger** [sickill/off-plugin#46]
Version 1.2 worked perfectly with NB 8.0.2. Since updating to 1.3.0.5 and NB 8.1, I have been unable to match **any** file, regardless of what pattern I type.

Regardless of the size of the project, clicking the Reindex button produces the "indexing project files" spinner for only the briefest fraction of a second. It appears as if it is not actually doing anything.

This is in the UI log at startup:

```
WARNING [org.netbeans.core.modules]: had to upgrade dependencies for module net.sickill.off: added = [module org.netbeans.modules.projectuiapi.base/1 > 1.78.0, module org.netbeans.api.templates > 1.0, module org.openide.util.ui > 9.3, module org.openide.filesystems.nb, module org.openide.filesystems.compat8, module org.netbeans.modules.editor.document > 1.0] removed = []; details: [#243100: Separate desktop-independent utilities, Separate projectuiapi into desktop and NetBeans independent and dependent parts, Separation of Parsing and Indexing APIs, Separation of desktop and cleanup, Templates API has been separated into its own module.]
```
and when I switch project in the OFF window I get this:

```
INFO [net.sickill.off.netbeans.NetbeansProject]: [OFF] ImportWorker started...
INFO [net.sickill.off.netbeans.NetbeansProject]: [OFF] SourceGroups: [/home/johny/repos/common, /home/johny/NetBeansProjects/common]
INFO [net.sickill.off.common.OffListModel]: [OFF] refiltering model
INFO [net.sickill.off.netbeans.NetbeansProject]: [OFF] ImportWorker finished.
```

but still no files match.

The settings for 8.1 were automatically imported from 8.0.2, if that makes a difference (but I have uninstalled and reinstalled the plugin multiple times, including from a manual download of the .nbm file — I assume this would clear the prefs and any cached data.)

Do you have any idea what the problem is? I've had to revert to NB 8.0.2 just to get some work done…

**Comment by markiewb** [comment]
@tinyclanger: There is no need to switch back to NB 8.0.2. 1.2 is compatible to 8.1 too. Get it here https://github.com/sickill/off-plugin/releases/download/v1.2/off-netbeans-1.2.nbm


> I assume this would clear the prefs and any cached data.

No such plugin specific feature is implemented. Start with a clean/new userdir if you want the default configuration.


> This is in the UI log at startup:

Nothing serious. Filed as #47


> I have been unable to match any file

INFO [net.sickill.off.netbeans.NetbeansProject]: [OFF] SourceGroups: [/home/johny/repos/common, /home/johny/NetBeansProjects/common]
looks strange. Which project type are you using? Can you provide such a sample project?

**Comment by tinyclanger** [comment]
The project is a PHP project, created from existing sources. The PHP files are in /home/johny/repos/common, but the actual nbproject folder is saved in /home/johny/NetBeansProjects/common.

![grab1](https://cloud.githubusercontent.com/assets/139183/14977753/bf8f758e-110e-11e6-92b3-af7f73a5cabd.png)

I've attached a copy of the project: [common.zip](https://github.com/sickill/off-plugin/files/246495/common.zip)

**Comment by markiewb** [comment]
@tinyclanger : Please try https://github.com/sickill/off-plugin/releases/tag/v1.3.1.0-SN and give me feedback

**Comment by tinyclanger** [comment]
That's working now — thanks!

**Comment by markiewb** [comment]
@Chris2011: Can you please also try the new version https://github.com/sickill/off-plugin/releases/tag/v1.3.1.0-SN ? If it still works for your use cases, I will release and publish the version

**Comment by markiewb** [comment]
Hopefully it works better. I will release and publish it now.

**Comment by Chris2011** [comment]
Sry, didn't have time to test. Will test the new release soon. Thx. :)
