### ISSUE TITLE
Use selected project from Node/File, when opening search dialog

### ISSUE THREAD

**Issue by beltrachi** [sickill/off-plugin#8]
The plugin shows files of last project when you close a project and open a new diferent project

Steps:
1. Open project A
2. Use off (it loads files first) and you can search
3. Close project A
4. Open project B
5. Use off (it does not show loading) and the files it shows are from last project.

**Comment by Chris2011** [comment]
It should detect the project from the selected file, where are you in atm or on the selected project inside the project window.

**Comment by markiewb** [comment]
See http://wiki.netbeans.org/DevFaqListenForOpeningClosingProject

**Comment by markiewb** [comment]
http://bits.netbeans.org/dev/javadoc/org-netbeans-modules-projectapi/org/netbeans/api/project/FileOwnerQuery.html#getOwner-org.openide.filesystems.FileObject-

**Comment by markiewb** [comment]
Same issue, if you change the git branch to another branch. New files are not found.

**Comment by markiewb** [comment]
Cannot be reproduced in 1.3. Close as invalid

**Comment by Chris2011** [comment]
When I have selected a project and open OFF, the JComboBox will not select the selected project, I have to switch manually. So when I select an other project and I open the OFF plugin, the JComboBox should select the selected project too, so it should change the project and idexing it (Would be better to index it before but this is an other thing).

The same should happen, if I open a file which is related to a specific project and I open OFF, it should figure out which project it is, like in the GoToFile dialog.

**Comment by markiewb** [comment]
Fixed in 1.3 https://github.com/sickill/off-plugin/commit/b31494b5341db4806b6e9e8e5db04681bcfdec53

**Comment by Chris2011** [comment]
Works like a charm.
