### ISSUE TITLE
Too slow first indexing

### ISSUE THREAD

**Issue by tobynet** [sickill/off-plugin#9]
When  I first open search window after booting NetBeans, it make index  too slow first time.
It has pre-index mode like automated index after booting NetBeans?

Thanks

**Comment by mjomble** [comment]
As of version 1.2, the files of the currently active project are automatically indexed when NetBeans starts, so it should be done by the time you first open the OFF dialog.

Indexing all projects is a bit trickier as the plugin currently only handles one active project at a time. I may look into changing that, though.

**Comment by mjomble** [comment]
I'll close this issue for now and perhaps explore the multiple project approach in #17.
